### ISSUE TITLE
Add back drupal/drupal-driver dependency

### ISSUE THREAD

**Issue by jhedstrom** [drush-ops/behat-drush-endpoint#9]
The dependency for `drupal/drupal-driver` was removed in #8, but it isn't clear why. If I run `composer require drupal/drupal-driver` in an empty directory, it's dev dependencies aren't pulled in.

This library utilizes code from that library, and can be installed independently of `drupal/drupal-extension`, so should mark the driver as a dependency.

I have a workaround for failing tests in https://github.com/jhedstrom/drupalextension/pull/483, but would prefer to not have to do that. Folks running this drush endpoint on remote servers would also encounter this missing dependency issue.

**Comment by greg-1-anderson** [comment]
I'll look into this. I removed the dependency so that it would be possible to move the behat-drush-endpoint from `require-dev` to `require`, and then use it to test sites that are installed with `composer install --no-dev`. This seems to be working fine, but it sounds like I missed some actual dependencies that are perhaps in code paths not used in my particular use-case.

I'll see if I can fix this by avoiding use of the `drupal/drupal-driver` code, as I'd like to be able to include just the behat-drush-endpoint without causing phpunit to be pulled in.

**Comment by jhedstrom** [comment]
phpunit shouldn't be pulled in via the `drupal/drupal-driver`, as it declares it as a dev dependency, not a normal dependency.

**Comment by greg-1-anderson** [comment]
Sorry for the delay here. I just put this back in the master branch. Seems fine. I'll make another stable tag soon; bug me if I do not.
